import type { LoomLayerPanelLabels } from "./types"

export const LOOM_LAYER_PANEL_LABELS_ZH_CN: LoomLayerPanelLabels = {
  title: "图层",
  search: "搜索图层",
  all: "全部",
  visible: "可见",
  current: "当前",
  empty: "没有匹配的图层",
  createGroup: "新建分组",
  addLayer: "添加图层",
  collapse: "收起图层面板",
  expand: "展开图层面板",
  featureCount: (count) => `${count.toLocaleString("zh-CN")} 个要素`,
  geometry: { polygon: "面", polyline: "线", point: "点" },
  selectLayer: (name) => `选择图层 ${name}`,
  locateLayer: (name) => `定位图层 ${name}`,
  openAttributeTable: (name) => `打开属性表 ${name}`,
  moreLayerActions: (name) => `更多图层操作 ${name}`,
  renameGroup: (name) => `重命名分组 ${name}`,
  showLayer: (name) => `显示图层 ${name}`,
  hideLayer: (name) => `隐藏图层 ${name}`,
}

export const LOOM_LAYER_PANEL_LABELS_EN: LoomLayerPanelLabels = {
  title: "Layers",
  search: "Search layers",
  all: "All",
  visible: "Visible",
  current: "Current",
  empty: "No matching layers",
  createGroup: "Create group",
  addLayer: "Add layer",
  collapse: "Collapse layer panel",
  expand: "Expand layer panel",
  featureCount: (count) => `${count.toLocaleString("en")} features`,
  geometry: { polygon: "Polygon", polyline: "Line", point: "Point" },
  selectLayer: (name) => `Select layer ${name}`,
  locateLayer: (name) => `Locate layer ${name}`,
  openAttributeTable: (name) => `Open attribute table for ${name}`,
  moreLayerActions: (name) => `More layer actions for ${name}`,
  renameGroup: (name) => `Rename group ${name}`,
  showLayer: (name) => `Show layer ${name}`,
  hideLayer: (name) => `Hide layer ${name}`,
}
