import { defineCategory, type ShowcaseEntry } from "./types"

const primitive = defineCategory("primitive")

export const primitiveShowcases = [
  primitive("accordion", "Accordion 折叠面板", () => import("./AccordionShowcase")),
  primitive("alert", "Alert 提示", () => import("./AlertShowcase")),
  primitive("avatar", "Avatar 头像", () => import("./AvatarShowcase")),
  primitive("badge", "Badge 徽标", () => import("./BadgeShowcase")),
  primitive("button", "Button 按钮", () => import("./ButtonShowcase")),
  primitive("copy-button", "Copy Button 复制按钮", () => import("./CopyButtonShowcase")),
  primitive("calendar", "Calendar 日历", () => import("./CalendarShowcase")),
  primitive("card", "Card 卡片", () => import("./CardShowcase")),
  primitive("checkbox", "Checkbox 复选框", () => import("./CheckboxShowcase")),
  primitive("color-input", "Color Input 颜色输入", () => import("./ColorInputShowcase")),
  primitive("combobox", "Combobox 组合框", () => import("./ComboboxShowcase")),
  primitive("command", "Command 命令面板", () => import("./CommandShowcase")),
  primitive("confirm-dialog", "Confirm Dialog 确认框", () => import("./ConfirmDialogShowcase")),
  primitive("dialog", "Dialog 对话框", () => import("./DialogShowcase")),
  primitive("dropdown-menu", "Dropdown Menu 下拉菜单", () => import("./DropdownMenuShowcase")),
  primitive("empty", "Empty 空状态", () => import("./EmptyShowcase")),
  primitive("field", "Field 表单字段", () => import("./FieldShowcase")),
  primitive("icon-button", "Icon Button 图标按钮", () => import("./IconButtonShowcase")),
  primitive("input", "Input 输入框", () => import("./InputShowcase")),
  primitive("input-group", "Input Group 输入组", () => import("./InputGroupShowcase")),
  primitive("label", "Label 标签", () => import("./LabelShowcase")),
  primitive("pagination", "Pagination 分页", () => import("./PaginationShowcase")),
  primitive("popover", "Popover 气泡卡片", () => import("./PopoverShowcase")),
  primitive("select", "Select 选择器", () => import("./SelectShowcase")),
  primitive("separator", "Separator 分割线", () => import("./SeparatorShowcase")),
  primitive("skeleton", "Skeleton 骨架屏", () => import("./SkeletonShowcase")),
  primitive("slider", "Slider 滑块", () => import("./SliderShowcase")),
  primitive("sonner", "Sonner 消息通知", () => import("./SonnerShowcase")),
  primitive("switch", "Switch 开关", () => import("./SwitchShowcase")),
  primitive("table", "Table 表格", () => import("./TableShowcase")),
  primitive("tabs", "Tabs 标签页", () => import("./TabsShowcase")),
  primitive("textarea", "Textarea 多行输入", () => import("./TextareaShowcase")),
  primitive("toggle", "Toggle 切换", () => import("./ToggleShowcase")),
  primitive("toggle-group", "Toggle Group 切换组", () => import("./ToggleGroupShowcase")),
  primitive("tooltip", "Tooltip 文字提示", () => import("./TooltipShowcase")),
  primitive("chart", "Chart 图表", () => import("./ChartShowcase")),
  primitive("collapsible", "Collapsible 折叠容器", () => import("./CollapsibleShowcase")),
  primitive("context-menu", "Context Menu 右键菜单", () => import("./ContextMenuShowcase")),
  primitive("json-viewer", "JSON Viewer 数据查看", () => import("./JsonViewerShowcase")),
  primitive("progress", "Progress 进度", () => import("./ProgressShowcase")),
  primitive("radio-group", "Radio Group 单选组", () => import("./RadioGroupShowcase")),
  primitive("sheet", "Sheet 侧边抽屉", () => import("./SheetShowcase")),
] satisfies readonly ShowcaseEntry[]
