import { Textarea } from "@registry/ui/textarea"
import { type ChangeEvent, useState } from "react"
import type { LocalizedDemoProps } from "./types"

const labels = {
  "zh-CN": {
    initialValue: "主干道来自 Q3 外业调查。",
    controlled: "受控",
    layerDescription: "图层描述",
    characters: (count: number) => `字符数：${count}`,
    readOnly: "只读",
    generatedByPipeline: "处理流水线生成。",
    disabledAndInvalid: "禁用与错误",
    disabled: "禁用",
    invalid: "错误",
  },
  en: {
    initialValue: "Primary roads imported from Q3 field survey.",
    controlled: "Controlled",
    layerDescription: "Layer description",
    characters: (count: number) => `Characters: ${count}`,
    readOnly: "Read only",
    generatedByPipeline: "Generated by processing pipeline.",
    disabledAndInvalid: "Disabled and invalid",
    disabled: "Disabled",
    invalid: "Invalid",
  },
}

export function TextareaOverviewDemo({ locale = "zh-CN" }: LocalizedDemoProps) {
  const demoLabels = labels[locale]
  const [value, setValue] = useState(demoLabels.initialValue)

  return (
    <div className="max-w-sm space-y-8">
      <section className="space-y-3" data-demo="textarea-controlled">
        <h4 className="font-mono text-sm font-semibold tracking-wide text-foreground uppercase">
          {demoLabels.controlled}
        </h4>
        <Textarea
          aria-label={demoLabels.layerDescription}
          rows={4}
          value={value}
          onChange={(event: ChangeEvent<HTMLTextAreaElement>) =>
            setValue(event.currentTarget.value)
          }
        />
        <p className="text-xs text-muted-foreground" data-demo="textarea-count">
          {demoLabels.characters(value.length)}
        </p>
      </section>

      <section className="space-y-3" data-demo="textarea-readonly">
        <h4 className="font-mono text-sm font-semibold tracking-wide text-foreground uppercase">
          {demoLabels.readOnly}
        </h4>
        <Textarea readOnly rows={3} value={demoLabels.generatedByPipeline} />
      </section>

      <section className="space-y-3" data-demo="textarea-disabled-invalid">
        <h4 className="font-mono text-sm font-semibold tracking-wide text-foreground uppercase">
          {demoLabels.disabledAndInvalid}
        </h4>
        <Textarea placeholder={demoLabels.disabled} rows={3} disabled />
        <Textarea aria-invalid placeholder={demoLabels.invalid} rows={3} />
      </section>
    </div>
  )
}
