const sidebars = {
  docs: [
    {
      type: "doc",
      id: "intro",
    },
    {
      type: "category",
      label: "Getting started",
      items: [
        "getting-started/getting-started-installation",
        "getting-started/getting-started-theming",
        "getting-started/getting-started-registry",
      ],
    },
    {
      type: "category",
      label: "Components",
      items: [{ type: "autogenerated", dirName: "components" }],
    },
    {
      type: "category",
      label: "Blocks",
      items: [{ type: "autogenerated", dirName: "blocks" }],
    },
  ],
}

export default sidebars
