import { Textarea } from "@registry/ui/textarea"
import { type ChangeEvent, useState } from "react"
import { useLocaleLabels } from "../use-locale-labels"

export type TextareaOverviewDemoLabels = {
  readonly initialValue: string
  readonly controlled: string
  readonly layerDescription: string
  readonly characters: (count: number) => string
  readonly readOnly: string
  readonly generatedByPipeline: string
  readonly disabledAndInvalid: string
  readonly disabled: string
  readonly invalid: string
}

export const zhTextareaOverviewLabels = {
  initialValue: "主干道来自 Q3 外业调查。",
  controlled: "受控",
  layerDescription: "图层描述",
  characters: (count: number) => `字符数：${count}`,
  readOnly: "只读",
  generatedByPipeline: "处理流水线生成。",
  disabledAndInvalid: "禁用与错误",
  disabled: "禁用",
  invalid: "错误",
} satisfies TextareaOverviewDemoLabels

export const enTextareaOverviewLabels = {
  initialValue: "Primary roads imported from Q3 field survey.",
  controlled: "Controlled",
  layerDescription: "Layer description",
  characters: (count: number) => `Characters: ${count}`,
  readOnly: "Read only",
  generatedByPipeline: "Generated by processing pipeline.",
  disabledAndInvalid: "Disabled and invalid",
  disabled: "Disabled",
  invalid: "Invalid",
} satisfies TextareaOverviewDemoLabels

export function TextareaOverviewDemo({ labels }: { readonly labels?: TextareaOverviewDemoLabels }) {
  const localizedLabels = useLocaleLabels({
    zh: zhTextareaOverviewLabels,
    en: enTextareaOverviewLabels,
  })
  const demoLabels = labels ?? localizedLabels
  const [value, setValue] = useState(demoLabels.initialValue)

  return (
    <div className="max-w-sm space-y-8" data-demo="textarea-overview">
      <section className="space-y-3" data-demo="textarea-controlled">
        <h4 className="font-mono text-xs tracking-widest text-muted-foreground uppercase">
          {demoLabels.controlled}
        </h4>
        <Textarea
          aria-label={demoLabels.layerDescription}
          rows={4}
          value={value}
          onChange={(event: ChangeEvent<HTMLTextAreaElement>) =>
            setValue(event.currentTarget.value)
          }
        />
        <p className="text-xs text-muted-foreground" data-demo="textarea-count">
          {demoLabels.characters(value.length)}
        </p>
      </section>

      <section className="space-y-3" data-demo="textarea-readonly">
        <h4 className="font-mono text-xs tracking-widest text-muted-foreground uppercase">
          {demoLabels.readOnly}
        </h4>
        <Textarea readOnly rows={3} value={demoLabels.generatedByPipeline} />
      </section>

      <section className="space-y-3" data-demo="textarea-disabled-invalid">
        <h4 className="font-mono text-xs tracking-widest text-muted-foreground uppercase">
          {demoLabels.disabledAndInvalid}
        </h4>
        <Textarea placeholder={demoLabels.disabled} rows={3} disabled />
        <Textarea aria-invalid placeholder={demoLabels.invalid} rows={3} />
      </section>
    </div>
  )
}
