import { Textarea } from "@registry/ui/textarea"
import { type ChangeEvent, useState } from "react"

export function TextareaOverviewDemo() {
  const [value, setValue] = useState("Primary roads imported from Q3 field survey.")

  return (
    <div className="max-w-sm space-y-8" data-demo="textarea-overview">
      <section className="space-y-3" data-demo="textarea-controlled">
        <h4 className="font-mono text-xs tracking-widest text-muted-foreground uppercase">
          Controlled
        </h4>
        <Textarea
          aria-label="Layer description"
          rows={4}
          value={value}
          onChange={(event: ChangeEvent<HTMLTextAreaElement>) =>
            setValue(event.currentTarget.value)
          }
        />
        <p className="text-xs text-muted-foreground" data-demo="textarea-count">
          Characters: {value.length}
        </p>
      </section>

      <section className="space-y-3" data-demo="textarea-readonly">
        <h4 className="font-mono text-xs tracking-widest text-muted-foreground uppercase">
          Read only
        </h4>
        <Textarea readOnly rows={3} value="Generated by processing pipeline." />
      </section>

      <section className="space-y-3" data-demo="textarea-disabled-invalid">
        <h4 className="font-mono text-xs tracking-widest text-muted-foreground uppercase">
          Disabled and invalid
        </h4>
        <Textarea placeholder="Disabled" rows={3} disabled />
        <Textarea aria-invalid placeholder="Invalid" rows={3} />
      </section>
    </div>
  )
}
