import { readFile, writeFile } from "node:fs/promises"
import { join, resolve } from "node:path"

const repoRoot = resolve(import.meta.dirname, "..")
const showcaseDir = join(repoRoot, "showcase/src/showcases")
const outputPath = join(
  repoRoot,
  "packages/docs/src/components/ShowcaseDemo/source-catalog.generated.ts",
)

async function catalogSources(): Promise<readonly [string, string][]> {
  const pairs: [string, string][] = []
  for (const catalogFile of ["primitive-catalog.ts", "block-catalog.ts"]) {
    const text = await readFile(join(showcaseDir, catalogFile), "utf8")
    const pattern = /"([a-z0-9-]+)"(?:\s*,\s*"[^"]*")*\s*,\s*\(\)\s*=>\s*import\("\.\/([^"]+)"\)/g
    for (const match of text.matchAll(pattern)) pairs.push([match[1], match[2]])
  }
  return pairs
}

const pairs = await catalogSources()
const entries: [string, string][] = []
const missing: string[] = []

for (const [name, moduleName] of pairs) {
  const file = `${moduleName}.tsx`
  let raw: string
  try {
    raw = await readFile(join(showcaseDir, file), "utf8")
  } catch {
    missing.push(name)
    continue
  }
  entries.push([name, raw])
}

if (missing.length > 0) {
  throw new Error(`Missing showcase sources for registry items: ${missing.join(", ")}`)
}

entries.sort(([a], [b]) => a.localeCompare(b))

const body = entries
  .map(([name, raw]) => `  ${JSON.stringify(name)}: ${JSON.stringify(raw)},`)
  .join("\n")
const module = `/* biome-ignore-all format: generated showcase source catalog */
// Generated by scripts/generate-showcase-sources.ts — do not edit.
export const showcaseSources: Record<string, string> = {
${body}
}
`

await writeFile(outputPath, module)
console.log(`Wrote ${entries.length} showcase sources -> ${outputPath}`)
